canvas=document.getElementById("myCanvas");
ctx=canvas.getContext("2d");
var colorblue="blue";
ctx.beginPath();
ctx.strokeStyle=colorblue;
ctx.lineWidth=2;
ctx.arc(200,250,40,0,2 *Math.PI);
ctx.stroke();
var coloryell="yellow";
ctx.beginPath();
ctx.strokeStyle=coloryell;
ctx.lineWidth=2;
ctx.arc(250,300,40,0,2 *Math.PI);
ctx.stroke();
var colorblack="black";
ctx.beginPath();
ctx.strokeStyle=colorblack;
ctx.lineWidth=2;
ctx.arc(300,250,40,0,2 *Math.PI);
ctx.stroke();
var colorgreen="green";
ctx.beginPath();
ctx.strokeStyle=colorgreen;
ctx.lineWidth=2;
ctx.arc(350,300,40,0,2 *Math.PI);
ctx.stroke();
var colored="red";
ctx.beginPath();
ctx.strokeStyle=colored;
ctx.lineWidth=2;
ctx.arc(400,250,40,0,2 *Math.PI);
ctx.stroke();